services:
  - type: web
    name: safi-check
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_SERVER
        value: safisanadb.database.windows.net
      - key: DB_NAME
        value: safidb
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MOCK_MODE
        value: True
